global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using SharyFi.WinUI.Common;
global using SharyFi.WinUI.ViewModels;
global using SharyFi.WinUI.Views;
global using WinUICommunity;
global using static SharyFi.WinUI.Common.AppHelper;
